name: Generate Snake Game

on:
  # Executa sempre que houver push no perfil ou a cada dia à meia-noite
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main  # ou 'master', dependendo do seu repositório

jobs:
  generate:
    name: Generate Snake SVG
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: PiexTi
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit and push the generated SVG
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "🐍 Atualiza SVG da cobrinha animada"
          add: "dist/*.svg"
